[package]
name = "virtual_ip_host"
version = "0.1.0"
authors = ["Hajime Fukuda <hajime.fukuda@me.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
map_struct = "0.2"
failure = "0.1.5"
futures-preview = "=0.3.0-alpha.17"
